# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "End to End Performance - Base Eval"

prompts: 
  - prompts.py:answer_query_base
  - prompts.py:answer_query_level_two
  - prompts.py:answer_query_level_three

providers:
  - id: anthropic:messages:claude-haiku-4-5
    label: "Haiku: T-0.0"
    config:
      max_tokens: 2500
      temperature: 0

  - id: anthropic:messages:claude-sonnet-4-5
    label: "3.5 Sonnet: T-0.0"
    config:
      max_tokens: 2500
      temperature: 0

tests: promptfoo_datasets/end_to_end_dataset.csv