name: Claude Model Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.ipynb'
      - '**.py'
      - '**.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  model-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Claude Model Validation
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: "/model-check"
          claude_args: |
            --allowedTools "Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(echo:*),Read,Glob,Grep,WebFetch"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}